import Prism from 'prismjs';
// Prism components (dependency order matters).
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-markup-templating';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-jsx';
import 'prismjs/components/prism-tsx';
import 'prismjs/components/prism-python';
import 'prismjs/components/prism-java';
import 'prismjs/components/prism-c';
import 'prismjs/components/prism-cpp';
import 'prismjs/components/prism-csharp';
import 'prismjs/components/prism-go';
import 'prismjs/components/prism-rust';
import 'prismjs/components/prism-ruby';
import 'prismjs/components/prism-php';
import 'prismjs/components/prism-swift';
import 'prismjs/components/prism-kotlin';
import 'prismjs/components/prism-dart';
import 'prismjs/components/prism-sql';
import 'prismjs/components/prism-yaml';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-powershell';
import 'prismjs/components/prism-scss';
import 'prismjs/components/prism-less';
import 'prismjs/components/prism-graphql';
import 'prismjs/components/prism-toml';
import 'prismjs/components/prism-ini';
import 'prismjs/components/prism-docker';
import 'prismjs/components/prism-nginx';
export const LANGUAGES = [
  { id: 'javascript', label: 'JavaScript' },
  { id: 'typescript', label: 'TypeScript' },
  { id: 'jsx', label: 'JSX (React)' },
  { id: 'tsx', label: 'TSX (React)' },
  { id: 'python', label: 'Python' },
  { id: 'java', label: 'Java' },
  { id: 'c', label: 'C' },
  { id: 'cpp', label: 'C++' },
  { id: 'csharp', label: 'C#' },
  { id: 'go', label: 'Go' },
  { id: 'rust', label: 'Rust' },
  { id: 'ruby', label: 'Ruby' },
  { id: 'php', label: 'PHP' },
  { id: 'swift', label: 'Swift' },
  { id: 'kotlin', label: 'Kotlin' },
  { id: 'dart', label: 'Dart' },
  { id: 'sql', label: 'SQL' },
  { id: 'json', label: 'JSON' },
  { id: 'yaml', label: 'YAML' },
  { id: 'bash', label: 'Bash / Shell' },
  { id: 'powershell', label: 'PowerShell' },
  { id: 'css', label: 'CSS' },
  { id: 'scss', label: 'SCSS' },
  { id: 'less', label: 'Less' },
  { id: 'graphql', label: 'GraphQL' },
  { id: 'html', label: 'HTML' },
  { id: 'xml', label: 'XML' },
  { id: 'toml', label: 'TOML' },
  { id: 'ini', label: 'INI' },
  { id: 'docker', label: 'Dockerfile' },
  { id: 'nginx', label: 'Nginx' },
  { id: 'plain', label: 'Plain Text' },
];

// mark languages whose prism grammar id differs from our id
const GRAMMAR_ID = { html: 'markup', xml: 'markup', docker: 'docker', plain: null, json5: 'json5' };

export function prismLangId(id) {
  if (id === 'plain') return null;
  return GRAMMAR_ID[id] || id;
}

export function hasGrammar(id) {
  const gid = prismLangId(id);
  if (!gid) return true;
  return !!Prism.languages[gid];
}

export function sampleFor(id) {
  const s = {
    javascript: [
      '// Deep clone using structured clone',
      'function deepClone(obj) {',
      '  const seen = new WeakMap();',
      '  function copy(o) {',
      "    if (o === null || typeof o !== 'object') return o;",
      '    if (seen.has(o)) return seen.get(o);',
      '    const clone = Array.isArray(o) ? [] : {};',
      '    seen.set(o, clone);',
      '    for (const key of Object.keys(o)) {',
      '      clone[key] = copy(o[key]);',
      '    }',
      '    return clone;',
      '  }',
      '  return copy(obj);',
      '}',
      '',
      "const data = { user: { name: 'Ada', tags: ['ai', 'code'] } };",
      'const copy = deepClone(data);',
      'console.log(copy === data);   // false',
    ].join('\n'),
    typescript: [
      "type Status = 'idle' | 'loading' | 'success' | 'error';",
      '',
      'interface Task<T> {',
      '  id: string;',
      '  status: Status;',
      '  result?: T;',
      '  startedAt: Date;',
      '}',
      '',
      'async function runTask<T>(',
      '  fn: () => Promise<T>,',
      '  timeoutMs = 5000',
      ') : Promise<Task<T>> {',
      "  const task: Task<T> = { id: crypto.randomUUID(), status: 'loading', startedAt: new Date() };",
      '  try {',
      '    const result = await Promise.race([',
      '      fn(),',
      "      new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), timeoutMs)),",
      '    ]);',
      "    return { ...task, status: 'success', result };",
      '  } catch (err) {',
      "    console.error('Task failed:', err);",
      "    return { ...task, status: 'error' };",
      '  }',
      '}',
    ].join('\n'),
    python: [
      'import asyncio',
      'from dataclasses import dataclass',
      '',
      '@dataclass',
      'class Sensor:',
      '    name: str',
      '    value: float = 0.0',
      '',
      'async def read_sensor(s: Sensor) -> None:',
      '    while True:',
      '        s.value = round(s.value + 1.5, 2)',
      '        print(f"{s.name}: {s.value}")',
      '        await asyncio.sleep(0.5)',
      '',
      'async def main():',
      '    sensors = [Sensor("temp"), Sensor("humidity")]',
      '    tasks = [asyncio.create_task(read_sensor(s)) for s in sensors]',
      '    await asyncio.gather(*tasks)',
      '',
      'asyncio.run(main())',
    ].join('\n'),
    go: [
      'package main',
      '',
      'import (',
      '	"fmt"',
      '	"sync"',
      ')',
      '',
      'type Counter struct {',
      '	mu sync.Mutex',
      '	n  int',
      '}',
      '',
      'func (c *Counter) Inc() {',
      '	c.mu.Lock()',
      '	defer c.mu.Unlock()',
      '	c.n++',
      '}',
      '',
      'func main() {',
      '	var c Counter',
      '	var wg sync.WaitGroup',
      '	for i := 0; i < 1000; i++ {',
      '		wg.Add(1)',
      '		go func() {',
      '			defer wg.Done()',
      '			c.Inc()',
      '		}()',
      '	}',
      '	wg.Wait()',
      '	fmt.Println("counter:", c.n)',
      '}',
    ].join('\n'),
    rust: [
      'use std::collections::HashMap;',
      '',
      'fn count_words(text: &str) -> HashMap<String, u32> {',
      '    let mut map = HashMap::new();',
      '    for word in text.split_whitespace() {',
      '        *map.entry(word.to_lowercase()).or_insert(0) += 1;',
      '    }',
      '    map',
      '}',
      '',
      'fn main() {',
      '    let sample = "the quick brown fox jumps over the lazy dog the fox";',
      '    let counts = count_words(sample);',
      '    for (word, n) in counts.iter().take(5) {',
      '        println!("{word}: {n}");',
      '    }',
      '}',
    ].join('\n'),
    html: [
      '<!DOCTYPE html>',
      '<html lang="en">',
      '  <head>',
      '    <meta charset="UTF-8" />',
      '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
      '    <title>Hello</title>',
      '  </head>',
      '  <body>',
      '    <main>',
      '      <h1>Welcome 👋</h1>',
      '      <button onclick="greet()">Click me</button>',
      '    </main>',
      '    <script>',
      "      function greet() { alert('Hello there!'); }",
      '    </script>',
      '  </body>',
      '</html>',
    ].join('\n'),
    css: [
      ':root {',
      '  --brand: #6366f1;',
      '  --radius: 12px;',
      '}',
      '',
      '.card {',
      '  padding: 1.5rem;',
      '  border-radius: var(--radius);',
      '  background: linear-gradient(135deg, #fff, #eef2ff);',
      '  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);',
      '  transition: transform 0.2s ease;',
      '}',
      '',
      '.card:hover {',
      '  transform: translateY(-4px) scale(1.02);',
      '}',
    ].join('\n'),
    sql: [
      'SELECT',
      '    u.name,',
      '    COUNT(o.id) AS total_orders,',
      '    SUM(o.amount) AS revenue',
      'FROM users u',
      'LEFT JOIN orders o ON o.user_id = u.id',
      "WHERE u.created_at >= '2024-01-01'",
      'GROUP BY u.id, u.name',
      'HAVING COUNT(o.id) > 5',
      'ORDER BY revenue DESC',
      'LIMIT 10;',
    ].join('\n'),
    java: [
      'public class Fibonacci {',
      '    // Returns the nth Fibonacci number (iterative)',
      '    public static long fib(int n) {',
      '        if (n < 2) return n;',
      '        long a = 0, b = 1;',
      '        for (int i = 2; i <= n; i++) {',
      '            long next = a + b;',
      '            a = b;',
      '            b = next;',
      '        }',
      '        return b;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        for (int i = 0; i < 12; i++) {',
      '            System.out.printf("fib(%d) = %d%n", i, fib(i));',
      '        }',
      '    }',
      '}',
    ].join('\n'),
    bash: [
      '#!/usr/bin/env bash',
      '# Backup a directory with timestamps',
      'set -euo pipefail',
      '',
      'SRC="${1:-.}"',
      'DEST="${2:-./backup}"',
      'STAMP=$(date +%Y%m%d_%H%M%S)',
      '',
      'mkdir -p "$DEST"',
      'tar -czf "$DEST/backup_$STAMP.tar.gz" "$SRC"',
      'echo "Backed up $SRC -> $DEST/backup_$STAMP.tar.gz"',
    ].join('\n'),
    json: [
      '{',
      '  "name": "codestudio",',
      '  "version": "1.0.0",',
      '  "private": true,',
      '  "engines": {',
      '    "node": ">=20"',
      '  },',
      '  "scripts": {',
      '    "dev": "vite",',
      '    "build": "vite build"',
      '  }',
      '}',
    ].join('\n'),
    markdown: [
      '# CodeStudio 🚀',
      '',
      'Generate **beautiful** code videos in seconds.',
      '',
      '## Features',
      '- Syntax highlighting',
      '- Typewriter effect',
      '- Multiple export formats',
      '',
      '```js',
      'const nice = true;',
      '```',
    ].join('\n'),
    yaml: [
      '# deploy.yaml',
      'version: "3.8"',
      'services:',
      '  web:',
      '    image: nginx:alpine',
      '    ports:',
      '      - "8080:80"',
      '    environment:',
      '      - ENV=production',
      '    healthcheck:',
      '      test: ["CMD", "curl", "-f", "http://localhost"]',
      '      interval: 30s',
    ].join('\n'),
    php: [
        '<?php',
        '',
        'function slugify(string $text): string {',
        '    $text = preg_replace("/[^a-z0-9]+/", "-", strtolower(trim($text)));',
        '    return trim($text, "-");',
        '}',
        '',
        '$title = "Hello, CodeStudio 101!";',
        'echo slugify($title); // hello-codestudio-101'
    ].join('\n'),
    ruby: [
        '# FizzBuzz generator',
        'def fizzbuzz(n)',
        '  (1..n).map do |i|',
        '    next "FizzBuzz" if i % 15 == 0',
        '    next "Fizz" if i % 3 == 0',
        '    next "Buzz" if i % 5 == 0',
        '    i',
        '  end',
        'end',
        '',
        'puts fizzbuzz(20).join(", ")'
    ].join('\n'),
    swift: [
        'struct Point {',
        '    var x: Double',
        '    var y: Double',
        '',
        '    func distance(to other: Point) -> Double {',
        '        let dx = other.x - x',
        '        let dy = other.y - y',
        '        return (dx*dx + dy*dy).squareRoot()',
        '    }',
        '}',
        '',
        'let a = Point(x: 0, y: 0)',
        'let b = Point(x: 3, y: 4)',
        'print("Distance:", a.distance(to: b))'
    ].join('\n'),
    kotlin: [
        'fun main() {',
        '    val items = listOf("apple", "banana", "cherry")',
        '    val total = items',
        '        .filter { it.startsWith("b") }',
        '        .fold(0) { acc, _ -> acc + 1 }',
        '    println("Starts with b: $total")',
        '',
        '    val squares = (1..5).map { it * it }',
        '    println(squares)',
        '}'
    ].join('\n'),
    csharp: [
        'using System;',
        'using System.Linq;',
        '',
        'class Program',
        '{',
        '    static void Main()',
        '    {',
        '        var names = new[] { "Ada", "Grace", "Alan" };',
        '        var sorted = names.OrderBy(n => n).Select(n => n.ToUpper());',
        '        foreach (var name in sorted)',
        '            Console.WriteLine($"Hello, {name}!");',
        '    }',
        '}'
    ].join('\n'),
    dart: [
        'class Greeter {',
        '  final String name;',
        '  Greeter(this.name);',
        '',
        '  String greet() => "Hello, $name!";',
        '}',
        '',
        'void main() {',
        '  final greeter = Greeter("Dart");',
        '  print(greeter.greet());',
        '',
        '  final nums = [1, 2, 3, 4, 5];',
        '  final even = nums.where((n) => n.isEven).toList();',
        '  print(even);',
        '}'
    ].join('\n'),
    scss: [
        '$brand: #6366f1;',
        '$space: 1rem;',
        '',
        '@mixin card {',
        '  border-radius: 14px;',
        '  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);',
        '}',
        '',
        '.button {',
        '  @include card;',
        '  padding: $space $space * 2;',
        '  background: $brand;',
        '  color: #fff;',
        '',
        '  &:hover { filter: brightness(1.1); }',
        '}'
    ].join('\n'),
    graphql: [
        'type User {',
        '  id: ID!',
        '  name: String!',
        '  posts: [Post!]!',
        '}',
        '',
        'type Post {',
        '  title: String!',
        '  views: Int!',
        '}',
        '',
        'type Query {',
        '  user(id: ID!): User',
        '  recentPosts(limit: Int = 10): [Post!]!',
        '}'
    ].join('\n'),
    docker: [
        '# Multi-stage Node build',
        'FROM node:20-alpine AS build',
        'WORKDIR /app',
        'COPY package*.json ./',
        'RUN npm ci',
        'COPY . .',
        'RUN npm run build',
        '',
        'FROM nginx:alpine',
        'COPY --from=build /app/dist /usr/share/nginx/html',
        'EXPOSE 80',
        'CMD ["nginx", "-g", "daemon off;"]'
    ].join('\n'),
  };
  return s[id] || null;
}
